//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinBLP {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class BatReference : global::System.Configuration.ApplicationSettingsBase {
        
        private static BatReference defaultInstance = ((BatReference)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BatReference())));
        
        public static BatReference Default {
            get {
                return defaultInstance;
            }
        }
    }
}
